### PR TITLE
Automated Stress Tests, Multiple Keyspaces, many fixes

### PR DESCRIPTION
**Pull request by velvia**
This is unfortunately a big PR with multiple features dumped into one branch.  Reviewing commit by commit is recommended.  The overview:

- Addition of a new "stress" submodule, with several stress tests designed to be run either locally or in a cluster:  an ingestion stress test, a streaming/reading stress test, and an in-memory querying stress test.
- Ability to read from or write to a dataset in any keyspace, using the "database" option in both Spark and the CLI.  Internally, revamped stuff everywhere to refer to a `DatasetRef` instead of just a string Dataset name.
    - the metadata tables `dataset` and `columns` are presently stored in each keyspace as well.  However, in the future all the datasets and columns will be stored in a "FiloDB system" keyspace.
- Fix CLI bug where delete command only deleted the metadata.  Now it drops the chunks and chunkrowmap data tables as well.
- Added a new CLI `truncate` command to truncate datasets
- Fixed issue #84 with ingestion in Spark 1.5 after sort
- More CLI fixes, esp for creating a dataset on a dataset that already exists
- Enabled Akka message tracing / debug logging
- Started an internal "client" Scala API to abstract interfacing with the NodeCoordinatorActor
- Ingestion no longer flushes at the end of each partition write, but flushes at the end of entire ingestion command

NOTES:
- Discovered that in cluster mode the flushing wasn't really working properly.  This will be fixed in a subsequent PR.  For now there might be more unwritten data staying in memtables.

### CODE REVIEW

**Comment by java8964** [comment]
I can confirm the issue 84 of tungsten sorting in spark fixed in this PR.

**Comment by velvia** [comment]
Yong, many thanks!   Great to hear that.

**Comment by java8964** [comment]
hm, even this PR works with tungsten sort, but when ingesting data into same C* as tested before, I got following new error:

java.lang.NoSuchMethodError: com.datastax.driver.core.Session.newSimpleStatement(Ljava/lang/String;)Lcom/datastax/driver/core/SimpleStatement;
        at com.websudos.phantom.builder.query.ExecutableStatement$class.statement(ExecutableQuery.scala:54)
        at com.websudos.phantom.builder.query.Query.statement(Query.scala:69)
        at com.websudos.phantom.builder.query.ExecutableStatement$class.future(ExecutableQuery.scala:58)
        at com.websudos.phantom.builder.query.Query.future(Query.scala:69)
        at com.websudos.phantom.builder.query.ExecutableQuery$class.singleFetch(ExecutableQuery.scala:116)
        at com.websudos.phantom.builder.query.SelectQuery.singleFetch(SelectQuery.scala:48)
        at com.websudos.phantom.builder.query.SelectQuery.one(SelectQuery.scala:212)
        at filodb.cassandra.metastore.DatasetTable$$anonfun$getProjection$1.apply(DatasetTable.scala:90)

It looks like FiloDB fat jar in this PR includes "com.datastax.driver.core.Session" class. In our cluster, we always already includes "spark connector" jar released by datastax. The version is 1.5.0.
The compatible check can be found here:
https://github.com/datastax/spark-cassandra-connector

So it comes with the Cassandra Java driver 2.1

If I checked the version of the class, it looks like the method newSimpleStatement was NOT in version 2.1 and 3.0:
https://github.com/datastax/java-driver/blob/2.1/driver-core/src/main/java/com/datastax/driver/core/Session.java

The only version include this method is in version 2.2:
https://github.com/datastax/java-driver/blob/2.2/driver-core/src/main/java/com/datastax/driver/core/Session.java

But version 2.2 is never depended on in Spark Cassandra Connector.

In your sbt file, do you depend on Spark Cassandra connector? What version you depend on? Why C* Java Driver 2.2 being linked, and this cause some problem in our cluster environment.

In addition to that, I tried to start the spark-shell using following conf:

--conf spark.driver.userClassPathFirst=true --conf spark.executor.userClassPathFirst=true

Hope to use "filodb-spark-assembly-0.2.1-SNAPSHOT.jar" generated in this PR to override the classpath, but I still got the same error when I tried to do "save()" method.

**Comment by velvia** [comment]
Yong,

Nope we don’t depend on the Cass Connector.  

One option is to downgrade the version of Phantom to use the older java driver.  If you look in the dse-4.8 branch, you will see the older version of Phantom which uses the C* Java driver 2.1…

-Evan

**Comment by java8964** [comment]
The above error happens in the Driver side, now it is gone.

But on the spark executor side, I got the following error:

16/04/15 14:40:20 ERROR executor.Executor: Exception in task 3.3 in stage 4.0 (TID 131)
java.lang.ClassCastException: cannot assign instance of com.typesafe.config.impl.SimpleConfig to field filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1.filoConfig$1 of type com.typesafe.config.Config in instance of filodb.spark.FiloContext$$anonfun$insertIntoFilo$extension$1
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2006)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:72)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:98)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Is this due to our environment, or something else?

**Comment by velvia** [comment]
Weird.  What distro of spark u running?  The version of Datastax driver, Typesafe config has not changed.  Must be a conflict somewhere.  The JVM really needs dependency isolation. Sigh.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by java8964** [comment]
It is maybe our environment causing this. Let me dig it a little more.

**Comment by velvia** [comment]
@java8964 and others:  going to merge this PR to master.

**Comment by java8964** [comment]
Hi, Evan:

How to change the log level? I still try to find out more about losing update. I can produce it in-memory with 1M data on my laptop. I saw you add more "debug" level information, and I want to dump them when I test on my laptop. But I am kind of new of scala logging.

What I did is to start Spark locally on my laptop with following:

--conf spark.filodb.store=in-memory --conf spark.sql.shuffle.partitions=2 --packages com.databricks:spark-csv_2.10:1.4.0 --conf "spark.driver.extraJavaOptions=-Dlog.leve=debug"

But when I run the "save()", I didn't see any debug level logging from FiloDB in the console. But I don't see any logback.xml (is that the config file for scala slf4j?) in the classpath or jar. How do I change log level in scala in this case?

Thanks

**Comment by velvia** [comment]
You just configure spark logging.  In spark distro, log4j.properties.  Btw can you tell me how to repro on in-memory on laptop, I'll try it.  I added an ingestion stress test.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by java8964** [comment]
I cannot consistently reproduce it, but got very good chance (almost 1 in 3). The following test is done on pull-91.

I start my spark 1.5.2 like following:

spark-shell --jars /home/yzhang/java8964/FiloDB/spark/target/scala-2.10/filodb-spark-assembly-0.2.1-SNAPSHOT.jar --conf spark.filodb.store=in-memory --conf spark.sql.shuffle.partitions=2 --packages com.databricks:spark-csv_2.10:1.4.0 --driver-memory 3G --master local[2]

scala> import org.apache.spark.sql.SaveMode
import org.apache.spark.sql.SaveMode

scala> val csvDF = sqlContext.read.format("com.databricks.spark.csv").option("header", "true").option("inferSchema", "true").load("/home/yzhang/data/emails_1m.csv")
csvDF: org.apache.spark.sql.DataFrame = [Email: string, Domain: string, GlobalStop: int, RestrictedAddress: int, RestrictedDomain: int, RoleAddress: int, Active: int]

scala> val df = csvDF.withColumn("PartId", substring($"Email",0,2)).sort($"PartId").drop("PartId")
df: org.apache.spark.sql.DataFrame = [Email: string, Domain: string, GlobalStop: int, RestrictedAddress: int, RestrictedDomain: int, RoleAddress: int, Active: int]

scala> 

scala> df.write.format("filodb.spark").option("dataset", "poc1").option("row_keys", "Email").option("segment_key", "Domain").option("partition_keys", ":stringPrefix Email 2").mode(SaveMode.Overwrite).save()
                                                                                
scala> val poc1 = sqlContext.read.format("filodb.spark").option("dataset", "poc1").load()
poc1: org.apache.spark.sql.DataFrame = [RestrictedDomain: int, RestrictedAddress: int, Email: string, GlobalStop: int, RoleAddress: int, Domain: string, Active: int]

scala> csvDF.count
res2: Long = 1000000 
scala> poc1.count
res1: Long = 971397

So I just lost data in this case. Sometimes I will get 1,000,000, but if I run
"df.write.format("filodb.spark").option("dataset", "poc1").option("row_keys", "Email").option("segment_key", "Domain").option("partition_keys", ":stringPrefix Email 2").mode(SaveMode.Overwrite).save()" again in the same Spark shell, then load the poc1 again, I will lost data too.

I can reproduce this if I run the Spark-shell again 1 in 3. That's why I want to dump the debug log, to see if I can see any difference between runs.

If it helps, I attached the emails_1m.csv file in my test.
[emails_1m.csv.gz](https://github.com/tuplejump/FiloDB/files/228834/emails_1m.csv.gz)

**Comment by velvia** [comment]
Thanks. Actually the current head of pull-91 will probably leak records, because of a change in how the flush is done.  it’s actually merged to master, but I’m working on a fix on a new branch.  Will let you know when it’s available.

Can you verify something?  At the end of the ingestion, if this is all on your laptop, do the following in Spark shell:

import filodb.core.DatasetRef
filodb.spark.FiloSetup.client.ingestionStats(DatasetRef(dataset), 0)

(where dataset is the name of your dataset, like poc1)

The code above will print out how many rows remain in your memtable, which has not been flushed to the column store.

**Comment by java8964** [comment]
I created a new issue (92) with the debug logging enabled. Let me know if it helps.

Thanks

**Comment by java8964** [comment]
Here is the output:

scala> poc1.count
res3: Long = 997672

scala> import filodb.core.DatasetRef
import filodb.core.DatasetRef

scala> filodb.spark.FiloSetup.client.ingestionStats(DatasetRef("poc1"),0)
res4: filodb.coordinator.DatasetCoordinatorActor.Stats = Stats(19,19,0,3312,-1)

I expect poc1.count should be 1M, but only get 997672, so there is 2328 not matching in the count. Is the output matching with what you expect?

**Comment by velvia** [comment]
Hm thanks, not quite.  997672 + 3312 > 1M, so something is weird.  I'll try to reproduce, while at the same time adding instrumentation.

**Pull request merged**
