### PR TITLE
exportCSV for filo-cli

### PR DESCRIPTION
**Pull request by Shiti**

### CODE REVIEW

**Comment by velvia** [comment]
@Shiti thanks!  Some relatively minor comments but make sure you test with a large number of rows, like exporting a million rows to a file.

**Comment by velvia** [comment]
@Shiti good point.  Maybe we should encapsulate.  I think one way to do that is to have ColumnStore either take a Dataset, or more likely, a RichProjection.  Perhaps change KeyRange to embed a RichProjection.

**Comment by velvia** [comment]
I'll try to do that tomorrow morning.

**Comment by Shiti** [comment]
I tried export command with the limit as 1Mill and it got done in approx 4-5s

**Comment by velvia** [comment]
@Shiti thanks.  The reason why we still need a type parameter for scanSegments and readSegments is because `Segment` is typed in `[K]`.   We could possibly have a method that reads rows out, that does not need to be typed.  However, not all queries will be by row - in fact going forward we'd want to explore doing columnar type queries.

**Comment by velvia** [comment]
@Shiti you did a rebase and push?  i guess that's fine but then it's harder to see your revisions.  How about small fix for the whitespace and then we can merge, thanks!

**Comment by velvia** [comment]
@Shiti LGTM for most part, going to merge.

**Pull request merged**
